Fix the `build/endif_comment` check.
google/styleguide pull request #169
Opened 2016-08-11 15:11 UTC by arames

- The check needs to be run before we remove comments, otherwise valid
  lines will be found as invalid.
- A single character different from `/` after the spaces is enough to
  indicate an error.
- Also catch errors when only one `/` is present.
  (For example `#endif / MY_FILE_H`.)

Tested with:

    // Correct
    
    #endif// FOO_1
    #endif // FOO_2
    #endif  // FOO_3
    #endif  //
    #endif  // blargh
    #endif	// one tab
    #endif		// two tabs
    
    // Incorrect
    // Note that there are spaces and tabs below.
    #endif
    #endif 
    #endif          
    #endif	
    #endif							
    #endif x
    #endif xxx
    #endif / xxx

2016-08-11 15:20 UTC, arames commented
I should be on the CLA as alexandre.rames@gmail.com.

2016-08-11 15:21 UTC, arames commented
Updated the CLA.

2016-09-20 22:21 UTC, eglaysher requested changes
(Thank you for pinging me. Nobody actually is notified on the pull request queue.)

The main change looks good, but could you please put the test cases you have in the conversation into cpplint_unittest.py? You should be able to just add them to testBuildEndComment().

2016-09-21 10:16 UTC, arames commented
Thanks for the review. I have updated the unit tests, fixing what was necessary.

2016-09-21 17:03 UTC, eglaysher approved these changes

2016-09-21 17:03 UTC, merged

2016-09-21 17:03 UTC, eglaysher commented
Thanks!

2016-09-30 22:29 UTC, dirk-thomas commented
This patch makes comments behind `#endif` mandatory. Before they were optional. As far as I read the styleguide it doesn't say that every `#endif` must have a comment, e.g. this code snippet should be perfectly valid https://google.github.io/styleguide/cppguide.html#Preprocessor_Directives

2016-09-30 22:30 UTC, dirk-thomas commented
This patch makes comments behind `#endif` mandatory. Before they were optional. As far as I read the styleguide it doesn't say that every `#endif` must have a comment, e.g. this code snippet should be perfectly valid https://google.github.io/styleguide/cppguide.html#Preprocessor_Directives

**Update:** I just found that this has been reported in #186.

2016-09-30 22:35 UTC, eglaysher commented
Done.

2016-10-01 07:31 UTC, arames commented
"Before they were optional." That is only because the code was plainly broken and *never* checking the `#endif` for comments.

I see multiple options:
- Make this a warning instead of an error. (Not sure whether cpplint has warnings.)
- Do not fix this. Then we should *remove* this check and the related code, as it is currently not exercised.
- Reapply the fix. Then users should decide to not enable the associated check. That is what we did in our project, as we also felt that commenting after every `#endif` was too much.

2016-10-01 07:34 UTC, arames commented
Extending on my last bullet point. Currently having the check enabled does nothing. My patch was restoring the functionality that the check was designed to do. After the fix users need to decided whether they want this behaviour or not (which as far as I saw was the intended behaviour) by enabling or disabling the `build/endif_comment` check in their config.

2016-10-01 15:04 UTC, LukeCz commented
I agree with @arames. This behavior should be controlled by build/endif_comment check. This way anyone can decide if this check is needed or not. The same with multiple other checks that may be controversial for some people. I think the change should've not be reverted.

2016-10-04 00:58 UTC, LukeCz commented
@eglaysher, any thoughts on this issue?

2016-10-12 15:43 UTC, arames commented
I uploaded a revert of the revert at
https://github.com/google/styleguide/pull/193

PTAL

On Tue, 4 Oct 2016 at 01:58 Lukasz Czajczyk <notifications@github.com>
wrote:

> @eglaysher <https://github.com/eglaysher>, any thoughts on this issue?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/google/styleguide/pull/169#issuecomment-251269022>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ADnYaoHcdUsII0E2xkATcMq-v3XaNbY2ks5qwaS9gaJpZM4JiOal>
> .
>