CPPLINT.cfg root=setting is now relative to CFG file.
google/styleguide pull request #292
Opened 2017-11-09 21:56 UTC by iam

Also further improve the documentation and testing around ```--root```.

Previously the `root=setting` in the CFG file was treated identically
to passing ```--root=setting``` on the command line, which seems undesirable
since it depends on were CPPLINT.cfg was invoked from (for relative
paths).

Judging on settings such as ```'exclude_files'``` it seems within the spirit
to make the settings 'current working directory' contextual to the
same directory that CPPLINT.cfg is in.

This also makes execution consistent (picking up the "correct" settings)
regardless of the CWD when executing cpplint.py.

Example:

```
  echo 'root=..' >> /a/b/c/CPPLINT.cfg
  cd /
  cpplint.py /a/b/c/source_file.h
  # expects header guard of C_SOURCE_FILE_H_
```

However the old behavior would use '/../' = '/'
and incorrectly think the root was ``` 'A_B_C_SOURCE_FILE_H_'```.

2017-11-09 21:58 UTC, iam commented
Noticed root seems to be ignoring the directory of the CPPLINT.cfg so I uploaded this improvement:

@markmentovai

```
............................................................................................................................................................................
----------------------------------------------------------------------
Ran 172 tests in 0.683s

OK
```

2017-11-09 22:05 UTC, markmentovai requested changes

2017-11-09 22:05 UTC, markmentovai commented on cpplint/cpplint_unittest.py
> +    cpplint._root = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'nested')
80 columns

2017-11-10 00:38 UTC, iam commented
Fixed line length. Also fixed tests (forgot to 'git add' a file).

@markmentovai

2017-11-10 04:10 UTC, markmentovai approved these changes

2017-11-10 04:10 UTC, merged