Update style guideline URL
google/styleguide pull request #580
Opened 2020-10-06 15:16 UTC by FaresSalem

2020-10-06 15:43 UTC, FaresSalem commented
@googlebot I signed it!

2021-11-10 08:04 UTC, crypt096 approved these changes

2022-08-06 15:51 UTC, ProKashif approved these changes

2022-08-07 00:36 UTC, gpshead approved these changes

2022-08-07 00:37 UTC, merged

2022-08-08 14:56 UTC, The35rus commented
>

2022-08-08 14:57 UTC, The35rus requested changes
H

2024-10-13 09:02 UTC, SparrowWhiteElkRaven approved these changes

2024-10-13 09:04 UTC, SparrowWhiteElkRaven approved these changes