Unused list item
google/styleguide pull request #646
Opened 2021-08-16 23:31 UTC by at758

Unused list item after **Constants** under [Identifiers](https://google.github.io/styleguide/tsguide.html#identifiers)

2021-08-16 23:32 UTC, at758 commented
@googlebot I signed it!

2021-11-09 09:37 UTC, crypt096 approved these changes

2023-02-23 09:40 UTC, devvsakib requested changes
Your PR has a conflict. Please resolve the conflict first to get merged

2024-07-09 03:15 UTC, vapier commented
this should be fixed now with commit fd8c54856d66df2e2643e048344ae04d2cfdde9a

2024-07-09 03:15 UTC, closed without merging