Missing some titles in the jsguide.html file, under "3 Source file structure" title + Refreshing the page is slow.
google/styleguide pull request #655
Opened 2021-11-29 02:30 UTC by ellietms

Hi, I realised we are missing some titles under the 3 Source file structure section.
[JavascriptGuide](https://google.github.io/styleguide/jsguide.html)

it shows us 3.3 and we do not have 3.3.1, 3.3.2 but we have 3.3.3.
The Table contents are being created inside of the "include/jsguide.js" with pure javascript.
I added some comments that where I think the issue is happening.

one more thing is when I refresh the page, it takes longer for me to see all the links in my table of contents.
It is slow.

2023-02-23 09:42 UTC, devvsakib approved these changes
it's not mandatory to use a comma after the last element, also single quote or double quote doesn't matter. 
LGTM

2024-07-08 17:29 UTC, vapier requested changes
it's hard to tell functional from style changes in here.  please create a separate PR/commit for just the style changes.

2026-06-03 08:44 UTC, venu-dhannoju commented
It looks like the last review requested splitting the functional changes from the style-only changes to make review easier. Since there hasn't been activity for a while, is this PR still being worked on?

If so, updating the branch and separating the formatting changes into a dedicated commit (or PR) may help move the review forward.

2026-06-03 08:49 UTC, ellietms commented
> It looks like the last review requested splitting the functional changes from the style-only changes to make review easier. Since there hasn't been activity for a while, is this PR still being worked on?
> 
> If so, updating the branch and separating the formatting changes into a dedicated commit (or PR) may help move the review forward.

Hey, I do not think so

2026-06-03 15:47 UTC, vapier commented
if you don't intend on working on it, let's close it out

2026-06-03 15:47 UTC, closed without merging