Replaced unfamiliar words with simpler alternatives in the jsguide.
google/styleguide pull request #849
Opened 2024-08-24 12:37 UTC by SohanRaidev

Fixes #596

2025-03-27 17:02 UTC, vapier requested changes

2025-03-27 17:02 UTC, vapier commented on jsguide.html
> +  /**
there's now 2 `/**` markers (see previous line)

2025-03-27 17:02 UTC, vapier commented on jsguide.html
> +  * A useful type union, which is reused often.
please leave existing indentation as-is

2025-03-27 17:02 UTC, vapier commented on jsguide.html
> +
no trailing blank lines

2025-04-12 11:51 UTC, SohanRaidev commented
Thanks @vapier! Addressed all requested changes. Let me know if anything else needs to be fixed.

2025-04-14 00:12 UTC, vapier commented on jsguide.html
> +  /**
the indentation here is incorrect.  you can see it when you view the final rendered page.

leave the `/**` on the previous line with the `<pre>` HTML tags, and delete this one.

2025-04-17 08:36 UTC, vapier commented on jsguide.html
> +  * A useful type union, which is reused often.
the first line looks good now, but I think you want to delete 1 leading space from each line in this code example.  it's still off by one.

not sure if it's easy to preview your changes locally and compare to https://google.github.io/styleguide/jsguide.html#jsdoc-enum-and-typedef-comments.

2025-04-19 19:29 UTC, SohanRaidev commented on jsguide.html
> +  * A useful type union, which is reused often.
Done—removed the extra leading space in the <pre><code> block.

2025-04-24 18:22 UTC, merged

2025-04-24 18:22 UTC, vapier commented
thx bud